### ISSUE TITLE
How to download https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_v20_m200.tar

### ISSUE THREAD

**Issue by MingL196** [biobakery/MetaPhlAn#119] opened 2020-07-26 01:56 UTC
Hi,

I am looking for a way to download mpa_v20_m200.tar.

When I use MetaPhlAn2 to download the database, i.e.:

    metaphlan2.py --install --bowtie2db /home/ming/software/metaphlan_database

I get the following message:

"Downloading MetaPhlAn2 database
Please note due to the size this might take a few minutes

Downloading https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_v20_m200.tar
Enter username for Bitbucket.org HTTP at bitbucket.org: "

When I use my bitbucket account, I am denied access.

Any idea how I can get the https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_v20_m200.tar file?

Thanks.

**Comment by fbeghini** [comment] 2020-07-27 05:49
Duplicate of #89, please search in the past issues before posting.

**Closed by fbeghini** 2020-07-27 05:49 UTC
