### ISSUE TITLE
[Feature Request] Phylogenetic Tree

### ISSUE THREAD

**Issue by dansmith01** [biobakery/MetaPhlAn#102] opened 2020-06-17 19:56 UTC
Do you foresee posting a newick formatted phylogenetic tree for the taxa IDs in MetaPhlAn3? It would be helpful for enabling UniFrac distance matrix calculations.

**Comment by fbeghini** [comment] 2020-06-18 07:49
Duplicate of #92

**Closed by fbeghini** 2020-06-18 07:49 UTC
Labels: duplicate
